-- TODO: drop view and remove this script if not used
DROP VIEW IF EXISTS VIEW_INTERVALS;

CREATE VIEW IF NOT EXISTS VIEW_INTERVALS (
    ID,
    ROMAN_NUMERAL_SYMBOL,
    QUALITY_SYMBOL,
    BASE_QUALITY_SYMBOL,
    SEMITONES,
    OCTAVES,
    DIATONIC_POSITION
) AS
SELECT
    ref.ID AS ID,
    rn.SYMBOL AS ROMAN_NUMERAL_SYMBOL,
    (q.SYMBOL || ref.COMPOUND_DIATONIC) AS QUALITY_SYMBOL,
    (q.SYMBOL || ref.SIMPLE_DIATONIC) AS BASE_QUALITY_SYMBOL,
    ref.SEMITONES AS SEMITONES,
    ref.OCTAVES AS OCTAVES,
    deg.DIATONIC_POSITION AS DIATONIC_POSITION
FROM TBL_INTERVALS_REF ref
    INNER JOIN TBL_INTERVAL_QUALITIES q ON q.ID = ref.QUALITY_SYMBOL
    INNER JOIN ROMAN_NUMERALS rn ON rn.RN_ID = ref.SIMPLE_DIATONIC AND rn.IQ_ID = ref.QUALITY_SYMBOL
    INNER JOIN TBL_INTERVAL_DISTANCES dist ON dist.INTERVAL_ID = ref.SIMPLE_DIATONIC
    INNER JOIN DEGREES deg ON deg.DEG_ID = ref.SIMPLE_DIATONIC AND deg.RELATIVE_INDICATOR = 1
WHERE ref.SEMITONES <= 128;