DROP TABLE Supported_Chords;
CREATE TABLE Supported_Chords (Symbol VARCHAR(20) NOT NULL PRIMARY KEY, Intervals VARCHAR(100) NOT NULL);
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('maj', 'P1, M3, P5');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('maj7', 'P1, M3, P5, M7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('7', 'P1, M3, P5, m7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('add9', 'P1, M3, P5, M9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('m', 'P1, m3, P5');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('m7', 'P1, m3, P5, m7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('dim', 'P1, m3, d5');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('dim7', 'P1, m3, d5, d7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('aug', 'P1, M3, A5');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('sus4', 'P1, P4, P5');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('sus2', 'P1, M2, P5');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('maj9', 'P1, M3, P5, M7, M9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('maj13', 'P1, M3, P5, M7, M9, P11, M13');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('maj9♯11', 'P1, M3, P5, M7, M9, A11');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('maj13♯11', 'P1, M3, P5, M7, M9, A11, M13');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('6', 'P1, M3, P5, M6');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('6add9', 'P1, M3, P5, M6, M9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('maj7♯5', 'P1, M3, A5, M7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('maj7♭5', 'P1, M3, d5, M7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('m9', 'P1, m3, P5, m7, M9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('m11', 'P1, m3, P5, m7, M9, P11');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('m13', 'P1, m3, P5, m7, M9, P11, M13');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('m6', 'P1, m3, P5, M6');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('madd9', 'P1, m3, P5, M9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('m6add9', 'P1, m3, P5, M6, M9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('mM7', 'P1, m3, P5, M7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('mM9', 'P1, m3, P5, M7, M9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('m7♭5', 'P1, m3, d5, m7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('ø', 'P1, m3, d5, m7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('m7♯5', 'P1, m3, A5, m7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('9', 'P1, M3, P5, m7, M9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('11', 'P1, M3, P5, m7, M9, P11');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('13', 'P1, M3, P5, m7, M9, P11, M13');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('7sus4', 'P1, P4, P5, m7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('7♭5', 'P1, M3, d5, m7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('7♯5', 'P1, M3, A5, m7');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('7♭9', 'P1, M3, P5, m7, m9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('7♯9', 'P1, M3, P5, m7, A9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('7♭5♭9', 'P1, M3, d5, m7, m9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('7♭5♯9', 'P1, M3, d5, m7, A9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('7♯5♭9', 'P1, M3, A5, m7, m9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('7♯5♯9', 'P1, M3, A5, m7, A9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('9♭5', 'P1, M3, d5, m7, M9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('9♯5', 'P1, M3, A5, m7, M9');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('13♯11', 'P1, M3, P5, m7, M9, A11, M13');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('13♭9', 'P1, M3, P5, m7, m9, M13');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('11♭9', 'P1, M3, P5, m7, m9, P11');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('5', 'P1, P5');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('sus2sus4', 'P1, M2, P4, P5');
INSERT INTO Supported_Chords (Symbol, Intervals) VALUES ('-5', 'P1, M3, d5');