-- TODO: drop table and remove this script if not used
DROP TABLE IF EXISTS ROMAN_NUMERALS;

CREATE TABLE IF NOT EXISTS ROMAN_NUMERALS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  SYMBOL VARCHAR(10),
  RN_ID INTEGER,
  IQ_ID INTEGER,
  FOREIGN KEY (IQ_ID) REFERENCES TBL_INTERVAL_QUALITIES (ID)
);

INSERT INTO ROMAN_NUMERALS (SYMBOL, RN_ID, IQ_ID) VALUES
  ('i˚', 1, 4),
  ('i', 1, 2),
  ('i+', 1, 5),
  ('I˚', 1, 4),
  ('I', 1, 1),
  ('I', 1, 3),
  ('I+', 1, 5),
  ('ii˚', 2, 4),
  ('ii', 2, 2),
  ('ii+', 2, 5),
  ('II˚', 2, 4),
  ('II', 2, 1),
  ('II', 2, 3),
  ('II+', 2, 5),
  ('iii˚', 3, 4),
  ('iii', 3, 2),
  ('iii+', 3, 5),
  ('III˚', 3, 4),
  ('III', 3, 1),
  ('III', 3, 3),
  ('III+', 3, 5),
  ('iv˚', 4, 4),
  ('iv', 4, 2),
  ('iv+', 4, 5),
  ('IV˚', 4, 4),
  ('IV', 4, 1),
  ('IV', 4, 3),
  ('IV+', 4, 5),
  ('v˚', 5, 4),
  ('v', 5, 2),
  ('v+', 5, 5),
  ('V˚', 5, 4),
  ('V', 5, 1),
  ('V', 5, 3),
  ('V+', 5, 5),
  ('vi˚', 6, 4),
  ('vi', 6, 2),
  ('vi+', 6, 5),
  ('VI˚', 6, 4),
  ('VI', 6, 1),
  ('VI', 6, 3),
  ('VI+', 6, 5),
  ('vii˚', 7, 4),
  ('vii', 7, 2),
  ('vii+', 7, 5),
  ('VII˚', 7, 4),
  ('VII', 7, 1),
  ('VII', 7, 3),
  ('VII+', 7, 5),
  ('viii˚', 8, 4),
  ('viii', 8, 2),
  ('viii+', 8, 5),
  ('VIII˚', 8, 4),
  ('VIII', 8, 1),
  ('VIII', 8, 3),
  ('VIII+', 8, 5);
